2023-12-20 23:07:33,536 ERROR: Exception on /favicon.ico [GET] [in /home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 841, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 450, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 752, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 727, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/dargor/projects/microblog/app/errors/handlers.py", line 7, in not_found_error
    return render_template("errors/404.html"), 400
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/dargor/projects/microblog/app/templates/errors/404.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/dargor/projects/microblog/app/templates/base.html", line 42, in top-level template code
    {% set unread_message_count = current_user.unread_message_count() %}
  File "/home/dargor/projects/microblog/app/models.py", line 48, in unread_message_count
    query = sa.select(Message).where(Message.recipient == self, Message.timestamp > last_read_time)
UnboundLocalError: local variable 'last_read_time' referenced before assignment
2023-12-20 23:07:48,354 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:72]
2023-12-20 23:08:26,749 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:72]
2023-12-20 23:14:49,761 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:72]
2023-12-21 00:16:14,133 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:72]
2023-12-21 00:16:17,116 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:72]
2023-12-21 00:41:12,768 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:72]
