2023-12-20 19:45:38,478 ERROR: Exception on /user/susan/popup [GET] [in /home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/dargor/projects/microblog/app/main/routes.py", line 69, in user_popup
    return render_template('user_popup.html', user=user, form=form)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/dargor/projects/microblog/app/templates/user_popup.html", line 4, in template
    {% if user.about_me %}<p>{{ user.about_me }}</p>{{% endif %}}
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
2023-12-20 19:48:07,577 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:72]
2023-12-20 19:50:00,977 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:72]
2023-12-20 21:14:31,883 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:72]
2023-12-20 21:17:26,485 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:72]
2023-12-20 21:17:38,508 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:72]
2023-12-20 22:56:30,438 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:72]
