2023-12-19 15:06:07,711 ERROR: Exception on /auth/login [GET] [in /home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/dargor/projects/microblog/app/auth/routes.py", line 26, in login
    return render_template("login.html", title="Sign In", form=form)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: login.html
2023-12-19 15:12:02,640 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:67]
2023-12-19 15:50:20,655 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:72]
2023-12-20 19:19:38,052 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:72]
2023-12-20 19:22:33,220 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:72]
2023-12-20 19:23:25,561 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:72]
2023-12-20 19:23:55,106 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:72]
2023-12-20 19:27:14,723 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:72]
2023-12-20 19:28:45,916 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:72]
2023-12-20 19:30:05,316 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:72]
2023-12-20 19:30:16,520 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:72]
2023-12-20 19:35:46,471 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:72]
2023-12-20 19:37:58,740 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:72]
2023-12-20 19:38:02,403 ERROR: Exception on /user/susan/popup [GET] [in /home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/dargor/projects/microblog/app/main/routes.py", line 69, in user_popup
    return render_template('user_popup.html', user=user, form=form)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/dargor/projects/microblog/app/templates/user_popup.html", line 4, in template
    {% if user.about_me %}<p>{{ user.about_me }}</p>{{% endif %}}
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
2023-12-20 19:39:18,259 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:72]
2023-12-20 19:42:38,204 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:72]
2023-12-20 19:43:39,541 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:72]
2023-12-20 19:43:43,112 ERROR: Exception on /user/susan/popup [GET] [in /home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/dargor/projects/microblog/app/main/routes.py", line 69, in user_popup
    return render_template('user_popup.html', user=user, form=form)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/dargor/projects/microblog/app/templates/user_popup.html", line 4, in template
    {% if user.about_me %}<p>{{ user.about_me }}</p>{{% endif %}}
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
2023-12-20 19:45:34,780 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:72]
