2023-12-18 12:23:17,137 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:52]
2023-12-18 12:25:54,302 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:52]
2023-12-18 12:26:10,591 ERROR: Exception on /edit_profile [GET] [in /home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/dargor/projects/microblog/app/routes.py", line 96, in edit_profile
    form = EditProfileForm(current_user.username)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/dargor/projects/microblog/app/forms.py", line 38, in __init__
    super.__init__(*args, **kwargs)
TypeError: descriptor '__init__' of 'super' object needs an argument
2023-12-18 12:29:13,490 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:52]
2023-12-18 12:36:05,719 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:52]
2023-12-18 15:22:09,474 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:52]
2023-12-18 15:22:16,878 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:52]
2023-12-18 15:35:37,480 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:52]
2023-12-18 15:35:42,088 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:52]
2023-12-18 15:35:56,077 ERROR: Exception on / [GET] [in /home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 865, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 1239, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/home/dargor/projects/microblog/app/routes.py", line 18, in before_request
    g.locale = str(get_locale())
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask_babel/__init__.py", line 259, in get_locale
    babel = get_babel()
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask_babel/__init__.py", line 46, in get_babel
    return app.extensions['babel']
KeyError: 'babel'
2023-12-18 15:35:56,386 ERROR: Exception on / [GET] [in /home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 865, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 1239, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/home/dargor/projects/microblog/app/routes.py", line 18, in before_request
    g.locale = str(get_locale())
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask_babel/__init__.py", line 259, in get_locale
    babel = get_babel()
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask_babel/__init__.py", line 46, in get_babel
    return app.extensions['babel']
KeyError: 'babel'
2023-12-18 15:35:56,461 ERROR: Exception on /favicon.ico [GET] [in /home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 865, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask/app.py", line 1239, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/home/dargor/projects/microblog/app/routes.py", line 18, in before_request
    g.locale = str(get_locale())
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask_babel/__init__.py", line 259, in get_locale
    babel = get_babel()
  File "/home/dargor/.local/share/virtualenvs/microblog-UE3ND_hc/lib/python3.10/site-packages/flask_babel/__init__.py", line 46, in get_babel
    return app.extensions['babel']
KeyError: 'babel'
2023-12-18 15:38:54,069 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:58]
2023-12-18 17:01:54,148 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:58]
2023-12-19 11:19:17,111 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:58]
2023-12-19 11:19:59,548 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:58]
2023-12-19 11:21:09,105 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:58]
2023-12-19 11:23:09,391 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:58]
2023-12-19 11:23:12,136 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:58]
2023-12-19 11:24:51,199 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:58]
2023-12-19 11:27:42,985 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:58]
2023-12-19 11:36:18,876 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:58]
2023-12-19 11:37:23,318 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:58]
2023-12-19 11:39:03,110 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:58]
2023-12-19 11:39:54,816 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:58]
2023-12-19 11:40:52,314 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:58]
2023-12-19 13:16:51,013 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:63]
2023-12-19 13:41:53,563 INFO: Microblog started [in /home/dargor/projects/microblog/app/__init__.py:64]
